config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    member do
      post :write_next_chapter
      post :finish_story
    end
  end
  root 'stories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chapter.rb
class Chapter
  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor :chapter_title, :synopsis, :chapter_detail, :chapter_number

  validates :chapter_title, presence: true
  validates :synopsis, presence: true
  validates :chapter_number, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def initialize(attributes = {})
    @chapter_title = attributes[:chapter_title]
    @synopsis = attributes[:synopsis]
    @chapter_detail = attributes[:chapter_detail]
    @chapter_number = attributes[:chapter_number]
  end

  def attributes
    {
      chapter_title: @chapter_title,
      synopsis: @synopsis,
      chapter_detail: @chapter_detail,
      chapter_number: @chapter_number
    }
  end
end

app/models/concerns/case_conversion.rb
module CaseConversion
  extend ActiveSupport::Concern

  class_methods do
    def camelcase_to_snakecase(data)
      data.transform_keys { |key| key.to_s.underscore.to_sym }
    end

    def snakecase_to_camelcase(data)
      data.transform_keys { |key| key.to_s.camelize(:lower) }
    end
  end
end

app/models/story.rb
class Story < ApplicationRecord
  validate :chapters_format

  include CaseConversion
  include UtilityMethods

  scope :writing, -> { where("chapters @> '[{\"chapter_detail\": null}]'") }
  scope :finished, -> { where.not(id: writing.pluck(:id)) }

  def chapters
    read_attribute(:chapters).map { |chapter_data| Chapter.new(chapter_data.symbolize_keys) }.sort_by(&:chapter_number)
  end

  def chapters=(attributes)
    write_attribute(:chapters, attributes.map { |attr| attr.symbolize_keys })
    @chapters = nil  # Reset the cached chapters array
  end

  def self.create_from_outline(story_outline)
    story = {
      title: story_outline['title'],
      outline: story_outline['outline'],
      chapters: story_outline['chapters'].each_with_index.map do |chapter, index|
        camelcase_to_snakecase(chapter).merge(chapter_detail: nil, chapter_number: index + 1)
      end
    }
    Story.create!(story)
  end

  def update_chapter(chapter_number, new_content)
    chapters_data = read_attribute(:chapters)
    chapter_index = chapters_data.find_index { |chapter| chapter['chapter_number'] == chapter_number }
    if chapter_index
      chapters_data[chapter_index].merge!(self.class.camelcase_to_snakecase(new_content))
      write_attribute(:chapters, chapters_data)
      save!
    else
      errors.add(:chapters, 'Invalid chapter number')
      false
    end
  end

  def find_first_nil_chapter
    unwritten_chapter = chapters.find { |chapter| chapter.chapter_detail.nil? }
    unwritten_chapter&.chapter_number
  end

  def find_chapter_by_number(chapter_number)
    chapters.find { |chapter| chapter.chapter_number == chapter_number }
  end

  def formatted_chapter_titles
    titles = chapters.map(&:chapter_title)
    array_list_to_string(titles)
  end

  private

  def chapters_format
    unless read_attribute(:chapters).is_a?(Array) && read_attribute(:chapters).all? { |chapter| chapter.is_a?(Hash) }
      errors.add(:chapters, 'must be an array of hashes')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :write_next_chapter, :finish_story]

  layout 'story', only: [:show]

  def index
    @writing_stories = Story.writing
    @finished_stories = Story.finished
  end

  def show
    if @story.chapters.any? { |chapter| chapter.chapter_detail.nil? }
      redirect_to edit_story_path(@story)
    end
  end

  def edit
  end

  def new
    @story = Story.new
  end

  def create
    key_elements = params[:story][:key_elements].reject(&:blank?)
    num_chapters = params[:story][:num_chapters].to_i

    service = StoryLlmService.new(@story)

    story_outline = service.generate_story_outline(key_elements, num_chapters)
    @story = Story.create_from_outline(story_outline)

    if @story&.persisted?
      redirect_to edit_story_path(@story), notice: 'Story created successfully.'
    else
      render :new
    end
  rescue StandardError => e
    Rails.logger.warn("Exception: #{e.message}")
    flash[:alert] = "Failed to create story: #{e.message}"
    render :new
  end

  def write_next_chapter
    service = StoryLlmService.new(@story)
    chapter_number, chapter_json = service.write_next_chapter(300)
    chapter_hash = Story.camelcase_to_snakecase(chapter_json) if chapter_json.present?

    if chapter_hash.present? &&
      chapter_hash&.dig(:chapter_detail).present? &&
      @story.update_chapter(chapter_number, chapter_json)

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("chapter_#{chapter_number}",
                                                    partial: "stories/chapter", locals: { chapter_hash: chapter_hash.merge(chapter_number: chapter_number) })
        end
        format.html { redirect_to edit_story_path(@story), notice: 'Next chapter written successfully.' }
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("flash",
                                                    partial: "layouts/flash", locals: { message: 'Failed to write the next chapter.' }),
                 status: :unprocessable_entity
        end
        format.html { redirect_to edit_story_path(@story), alert: 'Failed to write the next chapter.' }
      end
    end
  rescue StandardError => e
    Rails.logger.warn("Exception: #{e.message}")
    flash[:alert] = "Failed to write chapter: #{e.message}"
    render :new
  end

  def finish_story
    service = StoryLlmService.new(@story)

    success = true
    (1..@story.chapters.length).each do
      next unless @story.find_first_nil_chapter

      chapter_number, chapter_json = service.write_next_chapter(300)

      if chapter_json.present? && chapter_json&.dig('chapterDetail').present?
        @story.update_chapter(chapter_number, chapter_json)
      else
        success = false
        break
      end
    end

    if success
      redirect_to edit_story_path(@story), notice: 'Story finished successfully.'
    else
      redirect_to edit_story_path(@story), alert: 'Failed to finish the story.'
    end

  rescue StandardError => e
    Rails.logger.warn("Exception: #{e.message}")
    flash[:alert] = "Failed to finish story: #{e.message}"
    render :new
  end


  private

  def set_story
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <div class="flash <%= type %>">
      <p><%= message %></p>
      <button class="close-button" onclick="this.parentElement.style.display='none';">&times;</button>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryWriter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag "flash" do %>
      <%= render 'layouts/flash' %>
    <% end %>
    <%= yield(:banner) if content_for?(:banner) %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/story.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Story App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">  <%= javascript_importmap_tags %>
</head>
<body>
<% if content_for? :banner %>
  <header class="banner">
    <%= yield :banner %>
  </header>
<% end %>
<div class="layout">
  <%= yield %>
</div>
</body>
</html>

app/views/stories/_chapter.html.erb
<% chapter_hash = chapter.attributes if defined?(chapter) %>
<li id="chapter_<%= chapter_hash[:chapter_number] %>">
  <p><strong><%= chapter_hash[:chapter_title] %></strong>
    <% if chapter_hash[:chapter_detail].present? %>
      <button class="toggle-detail" data-target="chapter_detail_<%= chapter_hash[:chapter_number] %>">Show Details</button>
    <% else %>
      <span>- Not Written</span>
    <% end %>
  </p>
  <% if chapter_hash[:chapter_detail].present? %>
    <div id="chapter_detail_<%= chapter_hash[:chapter_number] %>" style="display: none;">
      <p><%= chapter_hash[:chapter_detail].gsub(/\n\n/, '</p><p>').gsub(/\n/, '</p><p>').html_safe %></p>
    </div>
  <% end %>
</li>

app/views/stories/edit.html.erb
<h1>Editing: <%= @story.title %></h1>
<h2>Outline:</h2>
<p><%= @story.outline %></p>
<h2>Chapters:</h2>
<div id="chapters-list">
  <% if @story.chapters.any? %>
    <ul>
      <% @story.chapters.each do |chapter| %>
        <%= render partial: 'chapter', locals: { chapter: chapter } %>
      <% end %>
    </ul>
  <% else %>
    <p>No chapters available.</p>
  <% end %>
</div>

<div id="actions">
  <% if @story.chapters.any? { |chapter| chapter.chapter_detail.nil? } %>
    <%= button_to 'Write Next Chapter', write_next_chapter_story_path(@story), method: :post, form: { data: { turbo_frame: "_top" } } %>
    <%= button_to 'Finish Story', finish_story_story_path(@story), method: :post, form: { data: { turbo_frame: "_top" } } %>
  <% else %>
    <%= link_to 'Read Story', story_path(@story) %>
  <% end %>
</div>

app/views/stories/index.html.erb
<h1>Stories</h1>
<%= link_to 'New Story', new_story_path %>

<h2>Currently Writing</h2>
<ul>
  <% @writing_stories&.each do |story| %>
    <li>
      <%= link_to story.title, edit_story_path(story) %>
    </li>
  <% end %>
</ul>

<h2>Finished Stories</h2>
<ul>
  <% @finished_stories&.each do |story| %>
    <li>
      <%= link_to story.title, story_path(story) %>
    </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= form_with model: @story, local: true, data: { turbo: false } do |form| %>
  <div id="key-elements-container">
    <%= form.label :key_elements, 'Key Elements (1 to 5)' %>
    <div class="key-element">
      <%= form.text_field :key_elements, name: 'story[key_elements][]', size: 30 %>
      <button type="button" class="remove-key-element">Remove</button>
    </div>
  </div>
  <button type="button" id="add-key-element">Add another element</button>

  <br><br>

  <div>
    <%= form.label :num_chapters, 'Number of Chapters (1 to 10)' %>
    <%= form.number_field :num_chapters, in: 1..10, required: true %>
  </div>

  <br>

  <div>
    <%= form.submit 'Generate Story Outline' %>
  </div>
<% end %>

app/views/stories/show.html.erb
<%= content_for :banner do %>
  <div class="banner-text">
    <h1><%= @story.title %></h1>
  </div>
<% end %>

<div class="content-with-sidebar">
  <div class="story">
    <h1><%= @story.title %></h1>
    <% @story.chapters.each do |chapter| %>
      <section class='chapter' id='chapter-<%= chapter.chapter_number %>'>
        <h2><%= chapter.chapter_title %></h2>
        <p><%= chapter.chapter_detail.gsub(/\n\n/, '</p><p>').gsub(/\n/, '</p><p>').html_safe %></p>
      </section>
    <% end %>
  </div>
</div>